### ISSUE TITLE
Passthrough over ARC works on C1 webOS 6.3.3

### ISSUE THREAD

**Issue by Nama** [lgstreamer/dts_restore#4]
Hi,
I'm very thankful for this.

I have an AVR which does ARC (not eARC) and after installing dts_restore, the sound is passtroughed to the AVR over ARC (stereo, ofc).

You stated, that passtrough is not possible. Is that not passtrough or does it just work on C1/webOS 6.3.3?
Since you force the downsampling, could it passtrough 5.1 to the AVR if the forced downsampling were removed?

**Comment by pbatard** [comment]
>  Is that not passtrough or does it just work on C1/webOS 6.3.3?

That's not passthrough. That's downsampling.

If you look at your AVR, which should be able to tell you what format it sees as input, you will see that it states that it's regular PCM (i.e. **already decoded** audio) and not DTS (i.e. direct passthrough audio that the AVR then needs to decode).

If it was passthrought, then you would get multichannel and not stereo.

**Comment by Nama** [comment]
Oh, that's how its meant. I understand now, thanks.
